### ISSUE TITLE
Server setup

### ISSUE THREAD

**Issue by niuhaoyu16** [umutsimsekli/sgd_tail_index#2]
Hi, this is amazing work. I have a quick question. What do you mean by " Make sure to replace the command that is specific to your server."

In the code, I saw the line below. How do I change it? I am new to this. THANKS.
launcher = "srun --nodes=1 --gres=gpu:1 --time=40:00:00 --mem=60G" # THIS IS AN EXAMPLE!!!

**Comment by umutsimsekli** [comment]
Hi! Thanks for the interest!

If you want to run the code on a server with multiple jobs, you might need to use the specific syntax of your system. That's an example syntax that worked for our system. Hope this helps.
